#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ENV_FILE:-${SCRIPT_DIR}/.env}"

# shellcheck disable=SC1091
source "${SCRIPT_DIR}/scripts/load_env.sh"

if [[ -f "${ENV_FILE}" ]]; then
  load_env_file "${ENV_FILE}"
fi

IMAGE_NAME="${CONTAINER_IMAGE_NAME:-${IMAGE_NAME:-whistx:latest}}"
CONTAINER_NAME="${CONTAINER_NAME:-whistx}"
APP_PORT="${APP_PORT:-${PORT:-8005}}"
APP_HOST="${APP_HOST:-${HOST:-0.0.0.0}}"
APP_ENTRYPOINT="${APP_ENTRYPOINT:-${APP:-server.app:app}}"
APP_WS_PATH="${APP_WS_PATH:-${WS_PATH:-/ws/transcribe}}"
DATA_DIR="${APP_DATA_DIR:-${DATA_DIR:-${SCRIPT_DIR}/data}}"
BUILD_POLICY="${CONTAINER_BUILD_POLICY:-missing}"
INSTALL_DIARIZATION="${CONTAINER_INSTALL_DIARIZATION:-${DIARIZATION_ENABLED:-0}}"

if [[ "${DATA_DIR}" != /* ]]; then
  DATA_DIR="${SCRIPT_DIR}/${DATA_DIR#./}"
fi

ASR_API_KEY_VALUE="${ASR_API_KEY:-${OPENAI_API_KEY:-}}"
ASR_BASE_URL_VALUE="${ASR_BASE_URL:-${OPENAI_BASE_URL:-}}"
ASR_MODEL_VALUE="${ASR_MODEL:-${WHISPER_MODEL:-whisper-1}}"
APP_UI_BANNERS_TEXT_VALUE="${APP_UI_BANNERS_TEXT:-}"
APP_UI_BANNERS_VALUE="${APP_UI_BANNERS:-${UI_BANNERS:-${WEBUI_BANNERS:-}}}"
ASR_DEFAULT_LANGUAGE_VALUE="${ASR_DEFAULT_LANGUAGE:-${DEFAULT_LANGUAGE:-ja}}"
ASR_DEFAULT_PROMPT_VALUE="${ASR_DEFAULT_PROMPT:-${DEFAULT_PROMPT:-}}"
ASR_DEFAULT_TEMPERATURE_VALUE="${ASR_DEFAULT_TEMPERATURE:-${DEFAULT_TEMPERATURE:-0.0}}"
ASR_CONTEXT_PROMPT_ENABLED_VALUE="${ASR_CONTEXT_PROMPT_ENABLED:-${CONTEXT_PROMPT_ENABLED:-1}}"
ASR_CONTEXT_MAX_CHARS_VALUE="${ASR_CONTEXT_MAX_CHARS:-${CONTEXT_MAX_CHARS:-1000}}"
ASR_MAX_QUEUE_SIZE_VALUE="${ASR_MAX_QUEUE_SIZE:-${MAX_QUEUE_SIZE:-8}}"
ASR_MAX_CHUNK_BYTES_VALUE="${ASR_MAX_CHUNK_BYTES:-${MAX_CHUNK_BYTES:-12582912}}"
DIARIZATION_FFMPEG_BIN_VALUE="${DIARIZATION_FFMPEG_BIN:-${FFMPEG_BIN:-ffmpeg}}"
LANGFUSE_ENABLED_VALUE="${LANGFUSE_ENABLED:-0}"
LANGFUSE_PUBLIC_KEY_VALUE="${LANGFUSE_PUBLIC_KEY:-}"
LANGFUSE_SECRET_KEY_VALUE="${LANGFUSE_SECRET_KEY:-}"
LANGFUSE_HOST_VALUE="${LANGFUSE_HOST:-}"
LANGFUSE_ENVIRONMENT_VALUE="${LANGFUSE_ENVIRONMENT:-}"
LANGFUSE_RELEASE_VALUE="${LANGFUSE_RELEASE:-}"
APP_DB_URL_VALUE="${APP_DB_URL:-}"
APP_SESSION_SECRET_VALUE="${APP_SESSION_SECRET:-change-me}"
APP_SESSION_DAYS_VALUE="${APP_SESSION_DAYS:-7}"
ENABLE_SELF_SIGNUP_VALUE="${ENABLE_SELF_SIGNUP:-0}"
APP_HISTORY_DIR_VALUE="${APP_HISTORY_DIR:-/app/data/history}"

if [[ -z "${ASR_API_KEY_VALUE}" ]]; then
  echo "[start.sh] ASR_API_KEY（または OPENAI_API_KEY）を設定してください" >&2
  exit 1
fi

mkdir -p "${DATA_DIR}/transcripts"
mkdir -p "${DATA_DIR}/history"

case "${BUILD_POLICY}" in
  always)
    echo "[start.sh] イメージを毎回ビルドします: ${IMAGE_NAME}" >&2
    docker build --build-arg INSTALL_DIARIZATION="${INSTALL_DIARIZATION}" -t "${IMAGE_NAME}" "${SCRIPT_DIR}"
    ;;
  missing)
    if docker image inspect "${IMAGE_NAME}" >/dev/null 2>&1; then
      echo "[start.sh] 既存イメージを再利用します: ${IMAGE_NAME}" >&2
    else
      echo "[start.sh] イメージがないためビルドします: ${IMAGE_NAME}" >&2
      docker build --build-arg INSTALL_DIARIZATION="${INSTALL_DIARIZATION}" -t "${IMAGE_NAME}" "${SCRIPT_DIR}"
    fi
    ;;
  never)
    if ! docker image inspect "${IMAGE_NAME}" >/dev/null 2>&1; then
      echo "[start.sh] BUILD_POLICY=never ですがイメージが存在しません: ${IMAGE_NAME}" >&2
      exit 1
    fi
    echo "[start.sh] 既存イメージを使用します: ${IMAGE_NAME}" >&2
    ;;
  *)
    echo "[start.sh] CONTAINER_BUILD_POLICY は always / missing / never のいずれかにしてください" >&2
    exit 1
    ;;
esac

docker run --rm \
  --name "${CONTAINER_NAME}" \
  -p "${APP_PORT}:${APP_PORT}" \
  -e ASR_API_KEY="${ASR_API_KEY_VALUE}" \
  -e ASR_BASE_URL="${ASR_BASE_URL_VALUE}" \
  -e ASR_MODEL="${ASR_MODEL_VALUE}" \
  -e SUMMARY_API_KEY="${SUMMARY_API_KEY:-}" \
  -e SUMMARY_BASE_URL="${SUMMARY_BASE_URL:-}" \
  -e SUMMARY_MODEL="${SUMMARY_MODEL:-gpt-4o-mini}" \
  -e SUMMARY_TEMPERATURE="${SUMMARY_TEMPERATURE:-0.2}" \
  -e SUMMARY_INPUT_MAX_CHARS="${SUMMARY_INPUT_MAX_CHARS:-16000}" \
  -e SUMMARY_SYSTEM_PROMPT="${SUMMARY_SYSTEM_PROMPT:-}" \
  -e SUMMARY_PROMPT_TEMPLATE="${SUMMARY_PROMPT_TEMPLATE:-}" \
  -e PROOFREAD_API_KEY="${PROOFREAD_API_KEY:-}" \
  -e PROOFREAD_BASE_URL="${PROOFREAD_BASE_URL:-}" \
  -e PROOFREAD_MODEL="${PROOFREAD_MODEL:-gpt-4o-mini}" \
  -e PROOFREAD_TEMPERATURE="${PROOFREAD_TEMPERATURE:-0.0}" \
  -e PROOFREAD_INPUT_MAX_CHARS="${PROOFREAD_INPUT_MAX_CHARS:-24000}" \
  -e PROOFREAD_SYSTEM_PROMPT="${PROOFREAD_SYSTEM_PROMPT:-}" \
  -e PROOFREAD_PROMPT_TEMPLATE="${PROOFREAD_PROMPT_TEMPLATE:-}" \
  -e APP_UI_BANNERS_TEXT="${APP_UI_BANNERS_TEXT_VALUE}" \
  -e APP_UI_BANNERS="${APP_UI_BANNERS_VALUE}" \
  -e APP_BRAND_TITLE="${APP_BRAND_TITLE:-whistx}" \
  -e APP_BRAND_TAGLINE="${APP_BRAND_TAGLINE:-高精度リアルタイム文字起こし}" \
  -e DIARIZATION_ENABLED="${DIARIZATION_ENABLED:-0}" \
  -e DIARIZATION_HF_TOKEN="${DIARIZATION_HF_TOKEN:-}" \
  -e DIARIZATION_MODEL="${DIARIZATION_MODEL:-pyannote/speaker-diarization-3.1}" \
  -e DIARIZATION_DEVICE="${DIARIZATION_DEVICE:-auto}" \
  -e DIARIZATION_SAMPLE_RATE="${DIARIZATION_SAMPLE_RATE:-16000}" \
  -e DIARIZATION_NUM_SPEAKERS="${DIARIZATION_NUM_SPEAKERS:-0}" \
  -e DIARIZATION_MIN_SPEAKERS="${DIARIZATION_MIN_SPEAKERS:-0}" \
  -e DIARIZATION_MAX_SPEAKERS="${DIARIZATION_MAX_SPEAKERS:-0}" \
  -e DIARIZATION_WORK_DIR="${DIARIZATION_WORK_DIR:-data/diarization}" \
  -e DIARIZATION_KEEP_CHUNKS="${DIARIZATION_KEEP_CHUNKS:-0}" \
  -e DIARIZATION_FFMPEG_BIN="${DIARIZATION_FFMPEG_BIN_VALUE}" \
  -e LANGFUSE_ENABLED="${LANGFUSE_ENABLED_VALUE}" \
  -e LANGFUSE_PUBLIC_KEY="${LANGFUSE_PUBLIC_KEY_VALUE}" \
  -e LANGFUSE_SECRET_KEY="${LANGFUSE_SECRET_KEY_VALUE}" \
  -e LANGFUSE_HOST="${LANGFUSE_HOST_VALUE}" \
  -e LANGFUSE_ENVIRONMENT="${LANGFUSE_ENVIRONMENT_VALUE}" \
  -e LANGFUSE_RELEASE="${LANGFUSE_RELEASE_VALUE}" \
  -e ASR_DEFAULT_LANGUAGE="${ASR_DEFAULT_LANGUAGE_VALUE}" \
  -e ASR_DEFAULT_PROMPT="${ASR_DEFAULT_PROMPT_VALUE}" \
  -e ASR_DEFAULT_TEMPERATURE="${ASR_DEFAULT_TEMPERATURE_VALUE}" \
  -e ASR_CONTEXT_PROMPT_ENABLED="${ASR_CONTEXT_PROMPT_ENABLED_VALUE}" \
  -e ASR_CONTEXT_MAX_CHARS="${ASR_CONTEXT_MAX_CHARS_VALUE}" \
  -e ASR_MAX_QUEUE_SIZE="${ASR_MAX_QUEUE_SIZE_VALUE}" \
  -e ASR_MAX_CHUNK_BYTES="${ASR_MAX_CHUNK_BYTES_VALUE}" \
  -e APP_PORT="${APP_PORT}" \
  -e APP_HOST="${APP_HOST}" \
  -e APP_ENTRYPOINT="${APP_ENTRYPOINT}" \
  -e APP_WS_PATH="${APP_WS_PATH}" \
  -e APP_DATA_DIR="/app/data" \
  -e APP_TRANSCRIPTS_DIR="/app/data/transcripts" \
  -e APP_DB_URL="${APP_DB_URL_VALUE}" \
  -e APP_SESSION_SECRET="${APP_SESSION_SECRET_VALUE}" \
  -e APP_SESSION_DAYS="${APP_SESSION_DAYS_VALUE}" \
  -e ENABLE_SELF_SIGNUP="${ENABLE_SELF_SIGNUP_VALUE}" \
  -e APP_HISTORY_DIR="${APP_HISTORY_DIR_VALUE}" \
  -v "${DATA_DIR}:/app/data" \
  "${IMAGE_NAME}"
